version: 0.2

phases:
  install:
    runtime-version:
      nodejs: 18
    commands:
      - npm install
  build:
    commands:
      - npm run-script build

artifacts:
  files:
    - frontend/public/**/*
    - frontend/src/**/*
    - frontend/package.json
    - backend/package.json
    - appspec.yml
    - scripts/**/*